language: julia
julia:
  - 1.0.2
  - nightly
  
matrix:
  allow_failures:
    - julia: nightly

notifications:
    email: false

branches:
  only:
    - master

codecov: true
after_success: 
  - julia -e 'cd(Pkg.dir("FaceCracker")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'