language: julia
julia:
  - nightly
  - 1.0
  - 1.0.2
  
notifications:
    email: false

branches:
  only:
    - master

after_success: 
  - julia -e 'cd(Pkg.dir("FaceCracker")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'